### ISSUE TITLE
Crear v1 jHipter NHG Sales Portal

### ISSUE THREAD

**Issue by poolebu** [poolebu/nhgSalesPortal#1]
### Todo
- [x] Generate Project choosing options

### Options
- [x] Elastic Search
- [x] Spanish and English, main english
- [x] Social Loging
- [x] Ecache
- [x] Websockets, see tracker
- [x] Multilenaguage
- [x] Https security
- [x] Integration tests for angular and spring
- [x] Performance test with Gatling

### Jhipster first test options

![captura de pantalla 2017-04-03 a las 2 44 42 pm](https://cloud.githubusercontent.com/assets/4500001/24609780/530ad13a-187c-11e7-83bb-ccd52679efa6.png)
